name: htmlgenerator-ci

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mypy
      run: pip install mypy
    - name: Check types
      run: mypy ${{ github.workspace }}
