name: htmlgenerator-ci

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - python-version: "3.7"
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-black pytest pytest-custom_exit_code black isort bandit safety mypy
        pip install -e .[all]
    - name: Lint with flake8
      run: flake8 .
    - name: Run black --check .
      run: black --check .
    - name: Run isort --check-only .
      run: isort --check-only --profile=black .
    - name: Run bandit
      run: bandit -c .bandit -r .
    - name: Run Safety
      # there is no allow-failure yet. see https://github.com/actions/toolkit/issues/399
      run: safety check || true
    - name: pytest
      run: pytest .
    - name: Check types
      run: mypy .
